const withSass = require('@zeit/next-sass');
const withLess = require('@zeit/next-less');
const withStylus = require('@zeit/next-stylus');
const withCSS = require('@zeit/next-css');

/*
 * This file was generated by Nx 9.2.0 to allow greater control over configuration
 * for Next apps. To optimize your configuration please update the following export
 * with only the style plugin you are using.
 *
 * e.g. module.exports = withCSS({ cssModules: false });
 */
module.exports = withStylus(
  withLess(
    withSass(
      withCSS({
        // Set this to true if you use CSS modules.
        // See: https://github.com/css-modules/css-modules
        cssModules: false
      })
    )
  )
);
